# [general]
import = [
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[env]
TERM = "xterm-256color" 

[shell]
program = "/bin/zsh"
args = ["-c", "tmux a -t main || tmux new -s main"]

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

# [window.padding]
# x = 5
# y = 5
